### ISSUE TITLE
[BUG]: New, order_list_id not found 

### ISSUE THREAD

**Issue by nilsps** [datawookie/binance#15]
### Description of the bug

Order_list_id does not exist when running spot_new_order.

### Steps To Reproduce

spot_new_order(
  order_type = "MARKET",
  symbol = "TRXUSDT",
  side = "SELL",
  quantity = 5
)

Ran in previous update. However, it does not longer run. Error returned is order_list_id doesn't exist; 

Traceback found in file:
[bug_binance2.txt](https://github.com/datawookie/binance/files/9143405/bug_binance2.txt)

**Comment by datawookie** [comment]
Ha! A classic case of "fix one thing, break something else".

Okay, I think I have this working now.

```r
spot_new_order(
  order_type = "MARKET",
  symbol = "TRXUSDT",
  side = "BUY",
  quantity = 500
)
```

That works fine.

```r
spot_new_order(
  order_type = "MARKET",
  symbol = "TRXUSDT",
  side = "BUY",
  quantity = 1
)
```

That fails with error because order size too small.

With the `test = TRUE` option the result should be a Boolean value.

If this still doesn't work, please add to the existing issues (depending on which problem persists!) rather than creating a new issue.

Thanks, Andrew.
